### ISSUE TITLE
运行了一下你的项目，打包放线上后直接白屏

### ISSUE THREAD

**Issue by gdlearn** [XNAL/ReadMore#10]
这些都不是我想关注的，为什么看你的代码，我有点熟悉的感觉呢， 感觉你的代码风格很像那个vue开源项目的bailicangdu/vue2-elm 40多k的star项目， 的风格很像哦，是不是有借鉴他其中的svg，api fetch 以及webpack打包配置的写法呢，哈哈哈哈。。。。如果是的话，难怪看的好熟悉的样子

**Comment by XNAL** [comment]
代码风格主要是受之前公司的影响，毕竟刚入职的时候是新手前端，写代码的时候就尽量去跟公司的代码风格保持一致。
