### ISSUE TITLE
部署之后图标没有，还有read页面不能正常访问

### ISSUE THREAD

**Issue by flyliao** [XNAL/ReadMore#4]
你好，非常感谢你的开源，不过我部署的时候图标不能展现，还有阅读页面不能正常访问，本地环境可以。
fetchChapterContent(chapterId) {
			api.getChapterContent(chapterId)
				.then(data => { 
					// this.readContent.push({
					// 	// contentTitle: data.title,
					// 	contentList: data.isVip ? ['vip章节，请到正版网站阅读'] : data.cpContent.split('\n')
					// });
					this.isLoading = false;
					this.$nextTick(function() {
						this.isShowPageLoading = false;
					})
				})
		},
这个data为undefind

**Comment by XNAL** [comment]
是不是没有在nginx中配置接口的代理？可以通过F12看下接口的提示。
