### ISSUE TITLE
nginx弄了，打开还是白屏

### ISSUE THREAD

**Issue by MukuroSama** [XNAL/ReadMore#5]
不是很懂vue，node那一套，不过本地环境都有。dist打包打出来了，按照部署静态资源站的那套，把dist放到nginx虚拟站点里了。浏览器访问还是白屏。
不是清楚你在“开发中遇到的一些问题”里写的那些是干嘛的，是不是必须要做的。
反正按我理解，这应该就是个静态网站啊，用了axios去访问追书神器的接口，本身不需要任何服务端的东西吧？

**Comment by XNAL** [comment]
需要的。因为部署在自己的服务器之后，使用axios接口会出现跨域的问题，导致接口访问出错。

**Comment by MukuroSama** [comment]
都做了，依然白屏。
nginx配置：
```
server {
    listen 80;
    server_name www.read.com;
    root E:/Coding/other/ReadMore/dist;
    location / {
        try_files $uri $uri/ @router;
    }
    location /api/ {
        proxy_pass http://api.zhuishushenqi.com/;
    }
    location @router {
        rewrite ^.*$ /index.html last;
    } 
}
```

**Comment by XNAL** [comment]
白屏的话就不是接口的问题了。应该是nginx或服务器配置的问题，可以排查下nginx配置以及服务器域名、端口等的配置信息。

**Comment by MukuroSama** [comment]
折腾你这个项目很多天了，依然没搞成。
我的目标就是能在本机部署一个可以打开域名就能看书的站（自用）
查了很多资料，也看了vue的文档（但没深入学习）
能在npm run dev下正常运行。但想打成dist包，部署到nginx里怎么都是白屏。
我又做了另一件事——
```
vue init webpack novel
```
生成新项目，把src目录替换进去，手动npm install安装package.json里的依赖包，把proxyTable里那两个接口的配置都拷进去。然后npm run dev，成了，可以正常访问。（但图标资源和页面表现有些不正常，可能是因为各种包的版本不同？）
同样是这个我“复制”过来的项目，npm run build，把之前的nginx配置复制一份，修改host，也能正常运行，不会白屏。
所以，白屏的原因到底是什么？是不是你的配置哪里有问题？没学过vue的菜鸟真的是查不出来了。
