### ISSUE TITLE
请问你的nginx反向代理的配置问题

### ISSUE THREAD

**Issue by Timmy-CN** [XNAL/ReadMore#9]
请问一下你的这个反向代理配置是怎么样的 http://chapter2.zhuishushenqi.com/chapter/http://vip.zhuishushenqi.com，要是可以的话，能贴一下你的nginx配置吗？

**Comment by XNAL** [comment]
nginx配置如下：
![image](https://user-images.githubusercontent.com/19232971/44651213-4d266180-aa1b-11e8-8712-8611faa0931f.png)
